### ISSUE TITLE
memo with payment

### ISSUE THREAD

**Issue by lucvanbraekel** [theproductiveprogrammer/luminate#6]
Many deposits require a "memo" field with a payment, but this wallet does not seem to support memo fields.

**Comment by theproductiveprogrammer** [comment]
Added memo support. Use `--memo 'Your Memo Text'` to add memo's to supported transactions. For example:

```
./luminate activate --from activeAccount --amt 2 --memo 'Activating now' inactiveAccount
```

Thanks for the suggestions @lucvanbraekel ! 👍
